name: CI/CD with Vercel

on:
  push:
    branches: 
      - main
  pull_request: 
    branches: [main]
    types: [closed]

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      YARN_ENABLE_IMMUTABLE_INSTALLS: false
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20 
      - name: Prepare Yarn 4 & Install dependencies
        run: |
          corepack enable
          corepack prepare yarn@4.9.2 --activate
          yarn install
      - run: yarn build
      - run: yarn turbo run test 
      - uses: actions/upload-artifact@v4
        with:
          name: build-output
          path: packages/ui/dist

  deploy-main:
    needs: test 
    runs-on: ubuntu-latest
    env:
      YARN_ENABLE_IMMUTABLE_INSTALLS: false
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - uses: actions/download-artifact@v4
        with:
          name: build-output
          path: packages/ui/dist
      - name: Prepare Yarn 4 & Install dependencies
        run: |
          corepack enable
          corepack prepare yarn@4.9.2 --activate
          yarn install
      - run: npm run build --workspace=main
      - run: npm install --global vercel 
      - name: Link Vercel Project
        run: vercel link --yes --project for-test-chart-admin --token ${{ secrets.VERCEL_TOKEN }} 
      - run: vercel pull --yes --environment=production --token ${{ secrets.VERCEL_TOKEN }}
      - run: vercel build --prod --token ${{ secrets.VERCEL_TOKEN }}
      - run: vercel deploy --prebuilt --prod --token ${{ secrets.VERCEL_TOKEN }}
